version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: soa_p
    ports:
      - "3308:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  usuarios-service:
    build: /usuarios-service 
    container_name: usuarios-service
    ports:
      - "3001:3001"
    networks:
      - my-network
    depends_on:
      - mysql

  juegos-service:
    build: /juegos-service  
    container_name: juegos-service
    ports:
      - "3002:3002"
    networks:
      - my-network
    depends_on:
      - mysql

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
