-- MySQL Script generated by MySQL Workbench
-- Fri Aug  9 23:27:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `region` VARCHAR(255) NULL DEFAULT NULL,
  `rol` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Juego` (
  `idJuego` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `clasificacion_edad` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_lanzamiento` DATE NULL DEFAULT NULL,
  `restriccion_region` VARCHAR(255) NULL DEFAULT NULL,
  `precio` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`idJuego`));


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`));


-- -----------------------------------------------------
-- Table `mydb`.`JuegoCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JuegoCategoria` (
  `Juego_idJuego` INT NOT NULL,
  `Desarrollador_idDesarrollador` INT NOT NULL,
  INDEX `fk_JuegoCategoria_Juego1_idx` (`Juego_idJuego` ASC) VISIBLE,
  PRIMARY KEY (`Juego_idJuego`, `Desarrollador_idDesarrollador`),
  CONSTRAINT `fk_JuegoCategoria_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `mydb`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JuegoCategoria_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `mydb`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`));


-- -----------------------------------------------------
-- Table `mydb`.`Desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desarrollador` (
  `idDesarrollador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idDesarrollador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JuegoCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JuegoCategoria` (
  `Juego_idJuego` INT NOT NULL,
  `Desarrollador_idDesarrollador` INT NOT NULL,
  INDEX `fk_JuegoCategoria_Juego1_idx` (`Juego_idJuego` ASC) VISIBLE,
  PRIMARY KEY (`Juego_idJuego`, `Desarrollador_idDesarrollador`),
  CONSTRAINT `fk_JuegoCategoria_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `mydb`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JuegoCategoria_Desarrollador1`
    FOREIGN KEY (`Desarrollador_idDesarrollador`)
    REFERENCES `mydb`.`Desarrollador` (`idDesarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
